from typing import Protocol


class TelemetryService(Protocol):
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def record_request(
        self, request_id: str, path: str, method: str, status_code: int
    ) -> None: ...
    def record_error(self, request_id: str, error: Exception) -> None: ...
    def set_user_context(self, user_id: int, email: str) -> None: ...
