from rastro.base.value_objects import ValueObject


class Email(ValueObject[str]): ...


class Username(ValueObject[str]): ...


class Name(ValueObject[str]): ...


class PasswordHash(ValueObject[str]): ...
