receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

exporters:
  clickhouse:
    endpoint: "${OTELCOL_CLICKHOUSE_ENDPOINT}"
    database: "${OTELCOL_CLICKHOUSE_DB}"
    username: "${OTELCOL_CLICKHOUSE_USERNAME}"
    password: "${OTELCOL_CLICKHOUSE_PASSWORD}"
  debug:
    verbosity: "detailed"

service:
  extensions:
    - "health_check"

  pipelines:
    traces:
      receivers:
        - "otlp"
      processors:
        - "batch"
      exporters:
        - "clickhouse"
        - "debug"

    # metrics:
    #   receivers:
    #     - "otlp"
    #   exporters:
    #     - "clickhouse"
    #     - "debug"

    # logs:
    #   receivers:
    #     - "otlp"
    #   exporters:
    #     - "clickhouse"
    #     - "debug"
