from rastro.base.value_object import ValueObject


class Email(ValueObject[str]): ...


class Username(ValueObject[str]): ...


class RawPassword(ValueObject[str]): ...


class HashedPassword(ValueObject[str]): ...
