apiVersion: "1"

datasources:
  - name: "ClickHouse"
    type: "grafana-clickhouse-datasource"
    url: "${GRAFANA_CLICKHOUSE_URL}"
    access: "proxy"
    jsonData:
      database: "${GRAFANA_CLICKHOUSE_DB}"
      username: "${GRAFANA_CLICKHOUSE_USER}"
    secureJsonData:
      password: "${GRAFANA_CLICKHOUSE_PASSWORD}"
