apiVersion: 1

datasources:
  - name: "ClickHouse"
    type: "grafana-clickhouse-datasource"
    access: "proxy"
    jsonData:
      protocol: "${RASTRO_GF_CLICKHOUSE_PROTOCOL}"
      host: "${RASTRO_GF_CLICKHOUSE_HOST}"
      port: "${RASTRO_GF_CLICKHOUSE_PORT}"
      username: "${RASTRO_GF_CLICKHOUSE_USER}"
    secureJsonData:
      password: "${RASTRO_GF_CLICKHOUSE_PASSWORD}"
    isDefault: true
